//  Created by TagCommander on 08/12/2022.
//  Version : 5.1.3
//
//  Copyright (c) 2022 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __CONSENT_GENERATED_H__
#define __CONSENT_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCConsentVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;

#define TC_USE_IDFA


#endif //__CONSENT_GENERATED_H__
