//  Created by TagCommander on 22/03/2023.
//  Version : 5.1.4
//
//  Copyright (c) 2023 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __CONSENT_GENERATED_H__
#define __CONSENT_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCConsentVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;

#define TC_USE_IDFA
#define TC_USE_IAB

#endif //__CONSENT_GENERATED_H__
